#!/usr/bin/env bash
set -e

DATA_DIR="/opt/data"
SOUL_FILE="${DATA_DIR}/SOUL.md"
CONFIG_FILE="${DATA_DIR}/config.yaml"
ENV_FILE="${DATA_DIR}/.env"

echo ">> [Hermes Agent] Starting up..."
echo ">> Data directory: ${DATA_DIR}"

# Ensure data directories exist
mkdir -p "${DATA_DIR}"/{sessions,memories,skills,cron,hooks,logs,skins}

# ── Environment file ───────────────────────────────────────────
# Hermes reads API keys and channel configs from .env file
if [ -f "${ENV_FILE}" ]; then
    echo ">> Loading environment from ${ENV_FILE}"
    set -a
    source "${ENV_FILE}"
    set +a
else
    echo ">> No .env file — using environment variables only"
fi

# ── SOUL.md bootstrap ─────────────────────────────────────────
if [ ! -f "${SOUL_FILE}" ]; then
    echo ">> Seeding default SOUL.md..."
    cat <<'EOF' > "${SOUL_FILE}"
# SOUL.md — Hermes Agent Identity

## 基本資訊
- **Name**: Hermes Agent
- **Version**: auto-create-openclaw integration
- **Role**: AI Assistant deployed by auto-create-openclaw platform

## 核心原則
- 使用繁體中文回覆
- 主動告知用戶目前進度與任何阻礙
- 不確定的時候要承認，不要胡說
- 承諾完成後要確實交付，不要半途而廢
- 每次對話結束後自動摘要到 memories/

## 記憶系統
- 長期記憶寫入 memories/ 目錄
- 每次對話結束後自動摘要
- 使用 memory/YYYY-MM-DD.md 格式記錄日常

## 禁用事項
- 不得執行任何具有破壞性的命令
- 不得未經確認就發送外部訊息
- 不得儲存明文密碼或 API keys
EOF
    echo ">> SOUL.md created"
fi

# ── Config.yaml bootstrap ─────────────────────────────────────
# Hermes uses YAML config for platform adapters
if [ ! -f "${CONFIG_FILE}" ]; then
    echo ">> Creating config.yaml..."

    # Determine which channels to enable
    local TELEGRAM_ON="false"
    local DISCORD_ON="false"
    local FEISHU_ON="false"
    local SLACK_ON="false"

    [ "${TELEGRAM_ENABLED:-false}" = "true" ]  && [ -n "${TELEGRAM_BOT_TOKEN:-}" ]  && TELEGRAM_ON="true"
    [ "${DISCORD_ENABLED:-false}" = "true" ]   && [ -n "${DISCORD_BOT_TOKEN:-}" ]   && DISCORD_ON="true"
    [ "${FEISHU_ENABLED:-false}" = "true" ]    && [ -n "${FEISHU_APP_ID:-}" ]        && FEISHU_ON="true"
    [ "${SLACK_ENABLED:-false}" = "true" ]      && [ -n "${SLACK_BOT_TOKEN:-}" ]      && SLACK_ON="true"

    cat <<EOF > "${CONFIG_FILE}"
# Hermes Agent Configuration
# Auto-generated by auto-create-openclaw

app:
  name: "Hermes Agent"
  version: "1.0.0"
  gateway:
    host: "0.0.0.0"
    port: ${HERMES_GATEWAY_PORT:-18790}
    ws_port: ${HERMES_WS_PORT:-18791}

model:
  provider: ${HERMES_MODEL_PROVIDER:-openai}
  model: ${HERMES_MODEL:-gpt-4o}
  api_key_env: ${HERMES_API_KEY_VAR:-OPENAI_API_KEY}

memory:
  enabled: true
  backend: filesystem
  path: /opt/data/memories

channels:
  telegram:
    enabled: ${TELEGRAM_ON}
    bot_token: \${TELEGRAM_BOT_TOKEN}

  discord:
    enabled: ${DISCORD_ON}
    bot_token: \${DISCORD_BOT_TOKEN}

  feishu:
    enabled: ${FEISHU_ON}
    app_id: \${FEISHU_APP_ID}
    app_secret: \${FEISHU_APP_SECRET}
    pairing_mode: ${FEISHU_PAIRING_MODE:-QR_SCAN}
    group_response_mode: ${FEISHU_GROUP_RESPONSE_MODE:-AT}

  slack:
    enabled: ${SLACK_ON}
    bot_token: \${SLACK_BOT_TOKEN}

logging:
  level: ${HERMES_LOG_LEVEL:-INFO}
  file: /opt/data/logs/hermes.log

skills:
  enabled: true
  path: /opt/data/skills
EOF
    echo ">> config.yaml created"
    echo ">> Channels: feishu=${FEISHU_ON} telegram=${TELEGRAM_ON} discord=${DISCORD_ON} slack=${SLACK_ON}"
fi

# ── Browser tools check ───────────────────────────────────────
if [ "${HERMES_ENABLE_BROWSER:-false}" = "true" ]; then
    echo ">> Browser tools ENABLED (higher memory usage)"
    export PLAYWRIGHT_BROWSERS_PATH=/opt/data/.playwright
else
    echo ">> Browser tools DISABLED"
fi

# ── Start Hermes Gateway ──────────────────────────────────────
echo ">> Starting Hermes Agent..."
echo ">> Gateway port: ${HERMES_GATEWAY_PORT:-18790}"
echo ">> Feishu: ${FEISHU_ENABLED:-false}, Telegram: ${TELEGRAM_ENABLED:-false}"

exec hermes gateway run \
    --host 0.0.0.0 \
    --port ${HERMES_GATEWAY_PORT:-18790} \
    --config ${CONFIG_FILE}
