#!/usr/bin/env bash
set -e

DATA_DIR="/opt/data"
SOUL_FILE="${DATA_DIR}/SOUL.md"
CONFIG_FILE="${DATA_DIR}/config.yaml"
ENV_FILE="${DATA_DIR}/.env"

echo ">> [Hermes Agent] Starting up..."
echo ">> Data directory: ${DATA_DIR}"

# Ensure data directories exist
mkdir -p "${DATA_DIR}"/{sessions,memories,skills,cron,hooks,logs,skins}

# ── Environment file check ───────────────────────────────────
# Hermes reads API keys from .env file
if [ -f "${ENV_FILE}" ]; then
    echo ">> Loading environment from ${ENV_FILE}"
    set -a
    source "${ENV_FILE}"
    set +a
else
    echo ">> No .env file found at ${ENV_FILE}"
    echo ">> API keys must be provided via environment variables"
fi

# ── SOUL.md bootstrap ─────────────────────────────────────────
if [ ! -f "${SOUL_FILE}" ]; then
    echo ">> Seeding default SOUL.md..."
    cat <<EOF > "${SOUL_FILE}"
# SOUL.md — Hermes Agent Identity

## 基本資訊
- **Name**: Hermes Agent
- **Version**: auto-create-openclaw integration
- **Role**: AI Assistant deployed by auto-create-openclaw platform

## 核心原則
- 使用繁體中文回覆
- 主動告知用戶目前進度與任何阻礙
- 不確定的時候要承認，不要胡說
- 承諾完成後要確實交付，不要半途而廢

## 記憶系統
- 長期記憶寫入 memories/ 目錄
- 每次對話結束後自動摘要到 memories/
- 使用 memory/YYYY-MM-DD.md 格式記錄日常

## 技能偏好
- Python > Bash > 其他語言（用最適合的工具解決問題）
- 使用 uv 管理 Python 環境
- 有不確定的 API 果前查文件

## 禁用事項
- 不得執行任何具有破壞性的命令（如 rm -rf /）
- 不得未經確認就發送外部訊息
- 不得儲存明文密碼或 API keys
EOF
    echo ">> SOUL.md created"
fi

# ── Config.yaml bootstrap ─────────────────────────────────────
if [ ! -f "${CONFIG_FILE}" ]; then
    echo ">> Creating default config.yaml..."
    cat <<EOF > "${CONFIG_FILE}"
# Hermes Agent Configuration
# Auto-generated by auto-create-openclaw

app:
  name: "Hermes Agent"
  version: "1.0.0"
  gateway:
    host: "0.0.0.0"
    port: ${HERMES_GATEWAY_PORT:-18790}
    ws_port: ${HERMES_WS_PORT:-18791}

model:
  provider: ${HERMES_MODEL_PROVIDER:-openai}
  model: ${HERMES_MODEL:-gpt-4o}
  api_key_env: ${HERMES_API_KEY_VAR:-OPENAI_API_KEY}

memory:
  enabled: true
  backend: filesystem
  path: /opt/data/memories

channels:
  telegram:
    enabled: ${TELEGRAM_ENABLED:-false}
    bot_token_env: TELEGRAM_BOT_TOKEN

  discord:
    enabled: ${DISCORD_ENABLED:-false}
    bot_token_env: DISCORD_BOT_TOKEN

logging:
  level: ${HERMES_LOG_LEVEL:-INFO}
  file: /opt/data/logs/hermes.log

skills:
  enabled: true
  path: /opt/data/skills
EOF
    echo ">> config.yaml created"
fi

# ── Browser tools check ───────────────────────────────────────
if [ "${HERMES_ENABLE_BROWSER:-false}" = "true" ]; then
    echo ">> Browser tools ENABLED (higher memory usage)"
    export PLAYWRIGHT_BROWSERS_PATH=/opt/data/.playwright
else
    echo ">> Browser tools DISABLED"
fi

# ── Health endpoint ────────────────────────────────────────────
# Hermes gateway provides /health endpoint when running

# ── Start Hermes Gateway ──────────────────────────────────────
echo ">> Starting Hermes Agent Gateway..."
echo ">> Gateway port: ${HERMES_GATEWAY_PORT:-18790}"
echo ">> WS port: ${HERMES_WS_PORT:-18791}"

# Run Hermes in gateway mode
exec hermes gateway run \
    --host 0.0.0.0 \
    --port ${HERMES_GATEWAY_PORT:-18790} \
    --ws-port ${HERMES_WS_PORT:-18791} \
    --config ${CONFIG_FILE}
